NUCL_COMPLEMENT_MAP = {"A":"T",
            "a": "t",
            "T":"A",
            "t": "a",
            "C":"G",
            "c": "g",
            "G":"C",
            "g": "c"}

NUCLEOTIDES = ["A", "T", "C", "G", "a", "t", "c", "g"]

AMINO_ACIDS_NAMES = {'A': 'Ala',
                     'R': 'Arg',
                     'N': 'Asn',
                     'D': 'Asp',
                     'V': 'Val',
                     'H': 'His',
                     'G': 'Gly',
                     'Q': 'Gln',
                     'E': 'Glu',
                     'I': 'Ile',
                     'L': 'Leu',
                     'K': 'Lys',
                     'M': 'Met',
                     'P': 'Pro',
                     'S': 'Ser',
                     'Y': 'Tyr',
                     'T': 'Thr',
                     'W': 'Trp',
                     'F': 'Phe',
                     'C': 'Cys'}

GRAVY_AA_VALUES = {'L': 3.8,
                   'K': -3.9,
                   'M': 1.9,
                   'F': 2.8,
                   'P': -1.6,
                   'S': -0.8,
                   'T': -0.7,
                   'W': -0.9,
                   'Y': -1.3,
                   'V': 4.2,
                   'A': 1.8,
                   'R': -4.5,
                   'N': -3.5,
                   'D': -3.5,
                   'C': 2.5,
                   'Q': -3.5,
                   'E': -3.5,
                   'G': -0.4,
                   'H': -3.2,
                   'I': 4.5}
